spring:
   mvc:
      view:
         prefix: /WEB-INF/jsp/
         suffix: .jsp
         
   datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      platform: postgres
      driverClassName: org.postgresql.Driver
   jpa:
      properties:
         hibernate:
            cache:
               use_second_level_cache: true
               use_query_cache: true
               region:
                  factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
            dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true

server:
   port: 8080


